// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPvR9qwHy_Ex-aG597El68Ud8K_XhXqu4',
    appId: '1:84963272655:web:73426bc643abced60d14ba',
    messagingSenderId: '84963272655',
    projectId: 'holbegram-4e897',
    authDomain: 'holbegram-4e897.firebaseapp.com',
    storageBucket: 'holbegram-4e897.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDjP2sY827hfmzKui8FmJeTtYpqi1Dgms',
    appId: '1:84963272655:android:b6e13aaf3b1cb4f30d14ba',
    messagingSenderId: '84963272655',
    projectId: 'holbegram-4e897',
    storageBucket: 'holbegram-4e897.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfwzLxNC_BRVbe1oJMSIIoNMVTFtMV9_A',
    appId: '1:84963272655:ios:079f3db808ebcbfc0d14ba',
    messagingSenderId: '84963272655',
    projectId: 'holbegram-4e897',
    storageBucket: 'holbegram-4e897.appspot.com',
    iosBundleId: 'com.example.holbegram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfwzLxNC_BRVbe1oJMSIIoNMVTFtMV9_A',
    appId: '1:84963272655:ios:f235dd002ab409db0d14ba',
    messagingSenderId: '84963272655',
    projectId: 'holbegram-4e897',
    storageBucket: 'holbegram-4e897.appspot.com',
    iosBundleId: 'com.example.holbegram.RunnerTests',
  );
}
